### PR TITLE
Adding Forum badges / icons

### PR DESCRIPTION
**Pull request by Stephen-Gates**
Work in progress 50+ icons to upload to separate local group directories. Will comment in PR when done.

@rgrp please double check icon file name before I upload the rest.

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
All files uploaded. 
UK used for Scotland.

**Comment by rufuspollock** [comment]
@Stephen-Gates looks good - are we ready to merge?

**Comment by Stephen-Gates** [comment]
Icons now being used as [badges](https://discuss.okfn.org/badges) in OK Forum.

**Comment by jgkim** [comment]
@Stephen-Gates Nice work!

**Pull request merged**
